[
    {
        "key": "dbln",
        "value": "%7B%2261578437177466%22%3A%22lSPGTAJ3%22%7D",
        "domain": "facebook.com",
        "path": "/login/device-based/",
        "hostOnly": false,
        "creation": "2025-08-06T07:17:55.013Z",
        "lastAccessed": "2025-08-06T07:17:55.014Z"
    },
    {
        "key": "datr",
        "value": "YP2JaPWJY_gb77sNhxgtAG3r",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-08-06T07:17:55.014Z",
        "lastAccessed": "2025-08-06T07:17:55.014Z"
    },
    {
        "key": "sb",
        "value": "YP2JaLMXVXp8EKR1wriaTv3W",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-08-06T07:17:55.014Z",
        "lastAccessed": "2025-08-06T07:17:55.014Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B680x360x2",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-08-06T07:17:55.014Z",
        "lastAccessed": "2025-08-06T07:17:55.014Z"
    },
    {
        "key": "ps_l",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-08-06T07:17:55.014Z",
        "lastAccessed": "2025-08-06T07:17:55.014Z"
    },
    {
        "key": "ps_n",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-08-06T07:17:55.014Z",
        "lastAccessed": "2025-08-06T07:17:55.014Z"
    },
    {
        "key": "pas",
        "value": "100042211012809%3AizU8oKzT9w%2C61575796191555%3A4takv0fLhQ%2C61578437177466%3AQjdAzjQQfY",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-08-06T07:17:55.014Z",
        "lastAccessed": "2025-08-06T07:17:55.014Z"
    },
    {
        "key": "locale",
        "value": "en_GB",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-08-06T07:17:55.014Z",
        "lastAccessed": "2025-08-06T07:17:55.014Z"
    },
    {
        "key": "c_user",
        "value": "61578437177466",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-08-06T07:17:55.014Z",
        "lastAccessed": "2025-08-06T07:17:55.014Z"
    },
    {
        "key": "xs",
        "value": "5%3A2MfsUxbZImr-gg%3A2%3A1754459425%3A-1%3A-1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-08-06T07:17:55.014Z",
        "lastAccessed": "2025-08-06T07:17:55.014Z"
    },
    {
        "key": "fr",
        "value": "0jGFpu7RBhXDQMeG3.AWdMAMyXdpyFg3JBZXDHjHRpdaJKvmxzAfbB9UDfWoTFooAslEs.Boif1g..AAA.0.0.BokwEb.AWeIh4pmipCoTSvw-uJV_1WFxR8",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-08-06T07:17:55.014Z",
        "lastAccessed": "2025-08-06T07:17:55.014Z"
    },
    {
        "key": "fbl_st",
        "value": "101638115%3BT%3A29241075",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-08-06T07:17:55.014Z",
        "lastAccessed": "2025-08-06T07:17:55.014Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A2886%3Btimestamp%3A1754464539",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-08-06T07:17:55.014Z",
        "lastAccessed": "2025-08-06T07:17:55.014Z"
    }
]
